/**
 * Defines the TypeScript interfaces for the Predicate Discovery IR.
 * This is based on the provided schema and example.
 */

/**
 * Represents a single predicate definition within the schema.
 */
export interface PredicateDefinition {
    /**
     * The snake_case name of the fact.
     * @example "hotel_price"
     */
    predicateName: string;

    /**
     * An array of argument names that define the structure of this fact.
     * The order of arguments is assumed to be significant.
     * @example ["hotel_id", "price"]
     */
    arguments: string[];

    /**
     * A plain English explanation of what this fact represents.
     */
    description: string;
}

/**
 * Represents the top-level Predicate Discovery Intermediate Representation (IR)
 * object generated by the AI.
 */
export interface PredicateDiscoveryIR {
    /**
     * An array of base fact predicates that model the core entities.
     */
    baseFactSchema: PredicateDefinition[];
}
